"use client";

import {
  PromptInputAtPalette as AtPalette,
  PromptInputAttachment as Attachment,
  PromptInputAttachmentRemove as AttachmentRemove,
  PromptInputAttachments as Attachments,
  PromptInputEditor as Editor,
  PromptInputFileInput as FileInput,
  PromptInputFileTrigger as FileTrigger,
  PromptInputLiveRegion as LiveRegion,
  PromptInputMenu as Menu,
  PromptInputMenuContent as MenuContent,
  PromptInputMenuFlyout as MenuFlyout,
  PromptInputMenuFlyoutTrigger as MenuFlyoutTrigger,
  PromptInputMenuTrigger as MenuTrigger,
  PromptInputModel as Model,
  PromptInputPaletteItem as PaletteItem,
  PromptInputProvider as Provider,
  PromptInputReferencedSource as ReferencedSource,
  PromptInputReferencedSourceRemove as ReferencedSourceRemove,
  PromptInputReferencedSources as ReferencedSources,
  PromptInputRoot as Root,
  PromptInputScreenshotTrigger as ScreenshotTrigger,
  PromptInputSkill as Skill,
  PromptInputSlashPalette as SlashPalette,
  PromptInputSource as Source,
  PromptInputSubmit as Submit,
} from "./components";

export const PromptInput = {
  Provider,
  Root,
  Editor,
  Submit,
  Menu,
  MenuTrigger,
  MenuContent,
  MenuFlyout,
  MenuFlyoutTrigger,
  FileInput,
  FileTrigger,
  ScreenshotTrigger,
  Attachments,
  Attachment,
  AttachmentRemove,
  ReferencedSources,
  ReferencedSource,
  ReferencedSourceRemove,
  Model,
  Skill,
  Source,
  SlashPalette,
  AtPalette,
  PaletteItem,
  LiveRegion,
};

export { PromptInputProvider, usePromptInputContext } from "./context";
export {
  fileExtensionLabel,
  formatFileSize,
  isLikelyTextFile,
  TEXT_LIKE_EXTENSIONS,
} from "./file-meta";
export { messageToFormData } from "./form-data";
export { captureScreenshot } from "./screenshot";

export type {
  CreateTokenElementOptions,
  PromptInputAtPaletteProps,
  PromptInputAttachment,
  PromptInputAttachmentError,
  PromptInputAttachmentErrorCode,
  PromptInputAttachmentKind,
  PromptInputAttachmentProps,
  PromptInputAttachmentRemoveProps,
  PromptInputAttachmentsProps,
  PromptInputEditorMode,
  PromptInputEditorProps,
  PromptInputFileInputProps,
  PromptInputFileTriggerProps,
  PromptInputFlyoutId,
  PromptInputItemAction,
  PromptInputLiveRegionProps,
  PromptInputMenuContentProps,
  PromptInputMenuFlyoutProps,
  PromptInputMenuFlyoutTriggerProps,
  PromptInputMenuProps,
  PromptInputMenuTriggerProps,
  PromptInputMessage,
  PromptInputModelDefinition,
  PromptInputModelProps,
  PromptInputPaletteItemProps,
  PromptInputReferencedSource,
  PromptInputReferencedSourceProps,
  PromptInputReferencedSourceRemoveProps,
  PromptInputReferencedSourcesProps,
  PromptInputRootProps,
  PromptInputRootState,
  PromptInputScreenshotTriggerProps,
  PromptInputSkillDefinition,
  PromptInputSkillProps,
  PromptInputSlashPaletteProps,
  PromptInputSourceDefinition,
  PromptInputSourceProps,
  PromptInputSourceSection,
  PromptInputStatus,
  PromptInputSubmitProps,
  PromptInputTriggerDefinition,
} from "./types";
